# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_addtobag(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, "h4 > .shop-now-button").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
        self.driver.find_element(
            By.CSS_SELECTOR,
            ".list-inline-item:nth-child(3) .toast-body .w-100"
          ).click()

    def test_bagcrudfunctions(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, "h4 > .shop-now-button").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-inline-item:nth-child(3) .fas").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 .increment-qty").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 .decrement-qty").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 .increment-qty").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 > .update-link > small").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 > #remove_14 > small").click()
        self.driver.find_element(By.CSS_SELECTOR, ".text-uppercase").click()

    def test_checkout(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, "h4 > .shop-now-button").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".list-inline-item:nth-child(3) > .text-info .fas"
          ).click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col > .btn-black > .text-uppercase").click()
        self.driver.find_element(By.ID, "id_full_name").click()
        self.driver.find_element(By.ID, "id_full_name").send_keys("test")
        self.driver.find_element(
            By.ID, "id_phone_number").send_keys("6161635432")
        self.driver.find_element(By.ID, "id_street_address1").click()
        self.driver.find_element(By.ID, "id_street_address1").click()
        element = self.driver.find_element(By.ID, "id_street_address1")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "id_country").click()
        self.driver.find_element(By.ID, "id-save-info").click()
        self.driver.switch_to.frame(1)
        self.driver.find_element(By.NAME, "cardnumber").click()
        self.driver.find_element(By.NAME, "cardnumber").send_keys(
            "4242 4242 4242 4242")
        self.driver.find_element(By.NAME, "exp-date").send_keys("04 / 24")
        self.driver.find_element(By.NAME, "cvc").send_keys("242")
        self.driver.find_element(By.NAME, "postal").send_keys("42424")
        self.driver.switch_to.default_content()
        self.driver.find_element(
            By.CSS_SELECTOR, "#submit-button > .font-weight-bold").click()

    def test_crudprofile(self):
        self.driver.get(
            "https://milestone-project-4-fsd.herokuapp.com/accounts/login/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12:nth-child(2) > .nav-link .fas").click()
        self.driver.find_element(By.CSS_SELECTOR, "#user-options .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_login").send_keys("test")
        self.driver.find_element(
            By.ID, "id_password").send_keys("testpassword")
        self.driver.find_element(By.CSS_SELECTOR, ".primaryAction").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#user-options .my-0").click()
        self.driver.find_element(By.LINK_TEXT, "My Profile").click()
        self.driver.find_element(By.ID, "id_default_phone_number").click()
        self.driver.find_element(
            By.ID, "id_default_phone_number").send_keys("564651651")
        self.driver.find_element(By.ID, "id_default_country").click()
        self.driver.find_element(By.ID, "id_default_country").click()
        dropdown = self.driver.find_element(By.ID, "id_default_country")
        dropdown.find_element(By.XPATH, "//option[. = 'Aruba']").click()
        self.driver.find_element(By.ID, "id_default_postcode").click()
        self.driver.find_element(
            By.ID, "id_default_postcode").send_keys("testy")
        self.driver.find_element(By.ID, "id_default_county").click()
        self.driver.find_element(
            By.ID, "id_default_county").send_keys("testyy")
        self.driver.find_element(By.ID, "id_default_town_or_city").click()
        self.driver.find_element(
            By.ID, "id_default_town_or_city").send_keys("testy")
        self.driver.find_element(By.ID, "id_default_street_address2").click()
        self.driver.find_element(
            By.ID, "id_default_street_address2").send_keys("testy")
        self.driver.find_element(By.ID, "id_default_street_address1").click()
        self.driver.find_element(
            By.ID, "id_default_street_address1").send_keys("testy")
        self.driver.find_element(By.CSS_SELECTOR, ".text-uppercase").click()
        self.driver.find_element(By.CSS_SELECTOR, "#user-options .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "button:nth-child(3)").click()

    def test_editquantity(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, "h4 > .shop-now-button").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".increment-qty > .icon").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-minus").click()

    def test_forgotpassword(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(By.CSS_SELECTOR, "#user-options .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_login").send_keys("test")
        self.driver.find_element(By.LINK_TEXT, "Forgot Password?").click()
        self.driver.find_element(By.ID, "id_email").click()
        self.driver.find_element(By.ID, "id_email").send_keys("test@test.com")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()

    def test_logoutandlogin(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(By.CSS_SELECTOR, "#user-options .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "button:nth-child(3)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#user-options > .text-center > div").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "id_login").send_keys("test")
        self.driver.find_element(
            By.ID, "id_password").send_keys("testpassword")
        self.driver.find_element(By.CSS_SELECTOR, ".primaryAction").click()

    def test_navbarlinks(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "By Price").click()
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "By Rating").click()
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "By Category").click()
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "All Products").click()
        self.driver.find_element(By.ID, "books-link").click()
        self.driver.find_element(By.LINK_TEXT, "Fiction").click()
        self.driver.find_element(By.ID, "books-link").click()
        self.driver.find_element(By.LINK_TEXT, "Non-Fiction").click()
        self.driver.find_element(By.ID, "books-link").click()
        self.driver.find_element(By.LINK_TEXT, "All Books").click()
        self.driver.find_element(By.ID, "accessories-link").click()
        self.driver.find_element(By.LINK_TEXT, "Bookmarks").click()
        self.driver.find_element(By.ID, "accessories-link").click()
        self.driver.find_element(By.LINK_TEXT, "E-readers").click()
        self.driver.find_element(By.ID, "accessories-link").click()
        self.driver.find_element(By.LINK_TEXT, "All Accessories").click()
        self.driver.find_element(By.ID, "specials-link").click()
        self.driver.find_element(By.LINK_TEXT, "New Arrivals").click()
        self.driver.find_element(By.ID, "specials-link").click()
        self.driver.find_element(By.LINK_TEXT, "Deals").click()
        self.driver.find_element(By.ID, "specials-link").click()
        self.driver.find_element(By.LINK_TEXT, "Clearance").click()
        self.driver.find_element(By.ID, "specials-link").click()
        self.driver.find_element(By.LINK_TEXT, "All Specials").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12:nth-child(1) strong").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#user-options-desktop .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(
            By.CSS_SELECTOR, "#user-options-desktop .my-0").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()

    def test_newslettersignup(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("test@test.com")
        self.driver.find_element(
            By.CSS_SELECTOR, ".text-white:nth-child(2)").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-12 > .shop-now-button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ml-2 > span").click()

    def test_productdetaillinks(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, ".navbar-toggler-icon").click()
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "All Products").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn > .text-uppercase").click()

    def test_register(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(By.CSS_SELECTOR, "#user-options .fas").click()
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(By.ID, "id_email").click()
        self.driver.find_element(By.ID, "id_email").send_keys("test@test.com")
        self.driver.find_element(By.ID, "id_email2").send_keys("test@test.com")
        self.driver.find_element(By.ID, "id_username").send_keys("test")
        self.driver.find_element(By.ID, "id_password1").send_keys("test")
        self.driver.find_element(By.ID, "id_password2").send_keys("test")
        self.driver.find_element(
            By.CSS_SELECTOR, "button:nth-child(8)").click()
        self.driver.find_element(By.ID, "id_username").click()
        self.driver.find_element(
            By.ID, "id_password1").send_keys("testpassword")
        self.driver.find_element(
            By.ID, "id_password2").send_keys("testpassword")
        self.driver.find_element(
            By.CSS_SELECTOR, "button:nth-child(8)").click()

    def test_review(self):
        self.driver.get("https://milestone-project-4-fsd.herokuapp.com/")
        self.driver.set_window_size(516, 728)
        self.driver.find_element(
            By.CSS_SELECTOR, ".navbar-toggler-icon").click()
        self.driver.find_element(By.ID, "all-products-link").click()
        self.driver.find_element(By.LINK_TEXT, "By Price").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
        self.driver.find_element(By.ID, "comment").click()
        self.driver.find_element(By.ID, "comment").send_keys("test")
        self.driver.find_element(By.ID, "review-privacy").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(8)").click()
        self.driver.close()
