# Generated by Django 3.2.13 on 2022-07-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_review_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='privacy',
        ),
    ]
